language: ruby
cache: bundler
gemfile: ./Gemfile

script:
  - bundle exec jekyll build 
## && htmlproofer --check-html --only-4xx  --http-status-ignore "403" ./_site 
## - bundle exec jekyll algolia --source ./ --destination ./_site --config ./_config.yml

env: 
  global: 
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master

rvm:
 - 2.4
