language: ruby
cache: bundler
gemfile: ./Gemfile

script:
  - bundle exec jekyll build 
  - bundle exec htmlproofer --check-html --only-4xx --http-status-ignore "403,404" ./_site 

env: 
  global: 
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master

rvm:
 - 2.4
